using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace TMClient.Controls
{
    /// <summary>
    /// Логика взаимодействия для AutoGeneratedAvatar.xaml
    /// </summary>
    public partial class AutoGeneratedAvatar : UserControl, INotifyPropertyChanged
    {
        private readonly static Dictionary<int, Color> Colors = new()
        {
            {0,(Color)ColorConverter.ConvertFromString("#F44336") },
            {1,(Color)ColorConverter.ConvertFromString("#E91E63") },
            {2,(Color)ColorConverter.ConvertFromString("#9C27B0") },
            {3,(Color)ColorConverter.ConvertFromString("#673AB7") },
            {4,(Color)ColorConverter.ConvertFromString("#3F51B5") },
            {5,(Color)ColorConverter.ConvertFromString("#00BCD4") },
            {6,(Color)ColorConverter.ConvertFromString("#009688") },
            {7,(Color)ColorConverter.ConvertFromString("#4CAF50") },
            {8,(Color)ColorConverter.ConvertFromString("#FFEB3B") },
            {9,(Color)ColorConverter.ConvertFromString("#FFC107") },
            {10,(Color)ColorConverter.ConvertFromString("#FF9800") },
            {11,(Color)ColorConverter.ConvertFromString("#FF5722") },
        };

        public static readonly DependencyProperty UserProperty =
        DependencyProperty.Register(nameof(User),
                                    typeof(User),
                                    typeof(AutoGeneratedAvatar),
                                    new PropertyMetadata(null, UserChanged));
        public User User
        {
            get => (User)GetValue(UserProperty);
            set
            {
                SetValue(UserProperty, value);
            }
        }

        public SolidColorBrush Color
        {
            get => color;
            set
            {
                color = value;
                OnPropertyChanged(nameof(Color));
            }
        }
        private SolidColorBrush color;

        public event PropertyChangedEventHandler? PropertyChanged;

        public void OnPropertyChanged(string name)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }

        public AutoGeneratedAvatar()
        {
            InitializeComponent();
        }

        private static void UserChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            ((AutoGeneratedAvatar)d).UserChanged((User)e.NewValue);
        }

        private void UserChanged(User newUser)
        {
            Color = PickColor(newUser);
        }

        private SolidColorBrush PickColor(User user)
        {
            return new SolidColorBrush(Colors[user.Id % Colors.Count]);
        }
    }
}
